### PR TITLE
Reran B970 and adding i5-2500 entry

### PR DESCRIPTION
**Pull request by Maxzor**

### CODE REVIEW

**Comment by rigred** [comment]
Verifying these results right now.

**Comment by rigred** [comment]
For some reason in the B970's test result there is an inconsistency on line 3046021.
Did you manually concatenate this file? If not there might be a bug in sandsifter or elsewhere.

Line 3046019 is essentially the same as 3046022.

But this is not significant. I will fix that manually.

image

**Comment by Maxzor** [comment]
No I did not operate on the log file AFAIR. I just came across some wonder that I am opening in a new issue.

**Comment by rigred** [comment]
Manually pulled in the B970 result and fixed the file. 
Closing the request now.

**Pull request closed without merging**
