### PR TITLE
Added Intel i3 3120M result

### PR DESCRIPTION
**Pull request by helospark**

### CODE REVIEW

**Comment by rigred** [comment]
Oooh this is getting interesting now. Thanks for testing and making the submission.
I will tomorrow also be testing an old i5-3210m I got so this data will make for an interesting comparison.

**Comment by rigred** [comment]
I'm quickly verifying your log file and will merge if it checks out :)

**Comment by rigred** [comment]
Merged!

Of note. Due to a screw up of mine, I've had to rebuild the entire git repo history + branches. Please forcefully update your fork. With a sledgehammer if you want to.

I apologize for that.

**Comment by helospark** [comment]
Thanks for the merge.
Will be interesting to see the diff between 3120M and 3210M :smiley:

**Comment by rigred** [comment]
@helospark Finally got around to adding that i5-3210m and some other CPU's.
Will have at least 4 more incoming soon.

Then first start on building a integrated DB. :D

**Pull request closed without merging**
