### PR TITLE
Intel Core i7 4702MQ

### PR DESCRIPTION
**Pull request by wouterwashere**
Added another CPU.

I did some quick lookup and found a Pentium 4 630 SL7Z9 laying around.

I'm intrigued to see if there is any difference between my Pentium 4 630 stepping N0 compared to the one already tested with stepping R0, so that will be the next run for me.

### CODE REVIEW

**Comment by rigred** [comment]
This test does not appear to be complete. There are non-hex blocks in the log
I expect all Intel & AMD CPU's logs to end with the 3 byte f3dfc7 intstruction.
This file ends with the 5 byte f20f0d5346 instruction.

Can you have a look at your sync and tick files to see where it ended? I suspect the files are in an inconsistent state. I bet the sync log wasn't fully written out to the log and may contain the complete data.

```
# insn tested: 1000509325
# artf found:  3046036
# runtime:     30:42:56.69
# seed:        4036853099
# arch:        64
# date:        2018-02-14 02:23:23
#
# cpu:
# processor	: 0
# vendor_id	: GenuineIntel
# cpu family	: 6
# model		: 60
# model name	: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
# stepping	: 3
# cpu MHz		: 2194.926
```
Note the inconsistencies to it's closest relative: (almost double runtime)

```
# insn tested: 1000509325
# artf found:  3046036
# runtime:     18:04:32.05
# seed:        2165617666
# arch:        64
# date:        2018-02-12 07:40:20
#
# cpu:
# processor     : 0
# vendor_id     : GenuineIntel
# cpu family    : 6
# model         : 60
# model name    : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
# stepping      : 3
# cpu MHz               : 3999.998
```

**Comment by wouterwashere** [comment]
I'll have a look at it. The runtime isn't comparative as I paused the process while running the notebook on battery. But maybe there are issues when pausing the test.

Anyway, couldn't get the Pentium 4 running in this system, so tried a Celeron 430 in stead. Really, it is slow. It took for more than two days to complete... But it ends with f3dfc7.

**Comment by rigred** [comment]
All checks out!
Merged.

**Comment by rigred** [comment]
Also I'm suprised that the E6300 and Celeron 430 are both Conroe architecture Chips.

**Pull request merged**
