### PR TITLE
i5-2500 completed

### PR DESCRIPTION
**Pull request by Maxzor**
Should be OK now!

### CODE REVIEW

**Comment by rigred** [comment]
Lovely! Merging now

**Comment by rigred** [comment]
It's amazing how the Intel logs are Max 227Mb. But the Ryzen logs are 1.4Gb. 
Just how much stuff did AMD cram in there?

**Comment by Maxzor** [comment]
A reading about the x86 diarrhea : https://blog.acolyer.org/2017/06/19/hardware-is-the-new-software/

**Comment by rigred** [comment]
I've read this before. But it's always appreciated :)

**Pull request merged**
