### PR TITLE
Added 4700mq

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
This adds the 4700mq test results following instructions from sandsifter-tests repo

### CODE REVIEW

**Comment by rigred** [comment]
Thanks for your submission.
It's quite surprising how small the log file for the 4700mq is.
200Mb only

**Comment by Lewiscowles1986** [comment]
It was shocking, I even double-checked the results and looked for error codes from the executable but it left with code zero (no error) and I run the command you have in this repo.

**Comment by Lewiscowles1986** [comment]
Fulfils #2 (for record keeping)

weird thing is the exact same command is logged, but ryzen seems to have run more instructions (albeit slowly)

image

**Comment by rigred** [comment]
The number of instructions executed significantly impacts the runtime.
In your case most guesses weren't executed. On Ryzen almost 18million instructions were executed out of ~1 billion tries.
It left me with a 1.4Gb Log file that I still haven't fully sorted out.

I may have to rerun this test though since it was from before most of the fixes were implemented.

**Pull request merged**
